### ISSUE TITLE
export many vCards in one file?

### ISSUE THREAD

**Issue by cmette** [jeroendesloovere/vcard#183] opened 2021-08-27 09:00 UTC
is it possible to write many vCards in a single output stream and send them to the browser as ->download()? do you have a quick example? Greetings Christian

**Comment by Rich-e-js** [comment] 2021-08-28 20:37
im also interested on this. i just simpli tried to add another name and number but i got an 'You can only set "name" once' error.

**Comment by neuhaus** [comment] 2021-11-19 10:36
This issue appears to be a direct duplicate of issue #170

**Comment by jeroendesloovere** [comment] 2021-11-24 20:57
vcard v2.0.0 will be able to handle this

**Closed by jeroendesloovere** 2021-11-24 20:57 UTC
