### ISSUE TITLE
How to load in the VCard php library?

### ISSUE THREAD

**Issue by osaki3b3** [jeroendesloovere/vcard#68] opened 2016-06-01 19:41 UTC
Hi

I have been trying to use this class with no success, I use it in a custom class I am calling it as follows

require_once($_SERVER['DOCUMENT_ROOT'].'/path/to/vcardclass/vcard-master/src/VCard.php');
use JeroenDesloovere\VCard\VCard;

$vcard = new VCard();
		$firstname = 'Jeroen';
		$lastname = 'Desloovere';
		$additional = '';
		$prefix = '';
		$suffix = '';

		// add personal data
	->	$vcard->addName($lastname, $firstname, $additional, $prefix, $suffix); <- when I get here everything breaks.

what Am I doing wrong?

**Comment by lighthouse72** [comment] 2016-06-01 19:53
Hi osaki3b3,

I had the same problem, found that including the php intl and change 
  return Transliterator::transliterate($value);
to
  return Transliterator_transliterate($value);
made some parts working. But found other parts are not working.

Later i found this line next line in src/VCard.php
  use Behat\Transliterator\Transliterator;
this can be found here https://github.com/Behat/Transliterator, but have not jet tested it.

I will try this tomorrow

**Comment by jeroendesloovere** [comment] 2016-06-02 06:36
Hi, looks like you downloaded the files, that is a difficult way.

The new way of loading in external php libraries works like this.

**1. Add a composer.json file in your root folder**
With the following content:
```json
{
    "require": {
        "php": ">=5.3.3",
        "jeroendesloovere/vcard": "^1.2"
    },
    "require-dev": {
        "phpunit/phpunit": "4.6.*"
    },
    "autoload": {
        "psr-4": { "JeroenDesloovere\\VCard\\": "src/" }
    }
}
```
**2. Then open your terminal (on MAC)**
And type:
```bash
composer install
```
Then the VCard class and all other dependencies (to make it work) will be installed.
**3. Requiring the vendor/autoload.php**
So all dependencies will be load in, into your file
```php
<?php
require_once __DIR__ . '/../vendor/autoload.php';
```
This should make everything work.

**Comment by lighthouse72** [comment] 2016-06-02 14:33
@jeroendesloovere thanks for the info.
After a php time-out of 5 years thinks change. First i needed to install the Composer, which gave me some problemen but works now. I installed the way it was intended in the README.md, but i needed the above info to get started.

Thanks for the info.

**Comment by jeroendesloovere** [comment] 2016-06-02 15:38
You're welcome.
Indeed, things change rapidly. I'm glad you could get it to work.

**Comment by osaki3b3** [comment] 2016-06-02 15:44
Thanks for your prompt reply jeroendesloovere. Will test as you suggest.

**Closed** 2016-06-06 12:48 UTC
Labels: invalid

**Comment by recurs1v0** [comment] 2020-01-30 21:28
If you have recently read this thread and you can not install Composer on your Server (by any reason or pre-requisite)

Here is how to do it in the "old and difficult" way.

1. Download https://github.com/Behat/Transliterator and UnZip
2. Copy all the files inside /src/ folder to the same folder your VCard class is located.
3. Change your Vcard.php Class on line 3 add the following:

`include ('Transliterator.php')`

Your whole VCard.php file should now look like this:

`
<?php
namespace JeroenDesloovere\VCard;

include('Transliterator.php');

/*
 * This file is part of the VCard PHP Class from Jeroen Desloovere.
 *
 * For the full copyright and license information, please view the license
 * file that was distributed with this source code.
 */

use Behat\Transliterator\Transliterator;

/**
 * VCard PHP Class to generate .vcard files and save them to a file or output as a download.
 */
class VCard
{
`
